import test from 'node:test';
import assert from 'node:assert/strict';
import { MCP_TOOL_BY_NAME, MCP_TOOLS, publicTool } from '../src/modules/mcp/tool-catalog.js';

// Business Process Flow authoring is the highest-risk surface in this catalog:
// a BPF is three artifacts that must agree, only two of them are writable, and
// the third is regenerated by the platform on activation. These assertions keep
// the tool contract honest about that.

const readTools = [
  'list_business_process_flows',
  'list_table_business_process_flows',
  'get_business_process_flow',
  'validate_business_process_flow',
  'get_business_process_flow_form_mapping_options'
];
const writeTools = [
  'create_business_process_flow',
  'patch_business_process_flow',
  'update_business_process_flow',
  'set_business_process_flow_state',
  'apply_business_process_flow_form_mappings'
];
const destructiveTools = [
  'delete_business_process_flow',
  'rollback_business_process_flow',
  'remove_business_process_flow_form_mappings'
];
const allTools = [...readTools, ...writeTools, ...destructiveTools];

test('BPF tools are typed, uniquely named, and risk classified', () => {
  assert.equal(new Set(MCP_TOOLS.map(tool => tool.name)).size, MCP_TOOLS.length);
  for (const name of allTools) {
    const tool = MCP_TOOL_BY_NAME.get(name);
    assert.ok(tool, `${name} is missing`);
    assert.equal(tool.inputSchema.type, 'object');
    assert.equal(tool.inputSchema.additionalProperties, false, `${name} must not accept unknown arguments`);
    const advertised = publicTool(tool);
    assert.equal(advertised.annotations.openWorldHint, false);
    assert.equal(advertised._meta['quickerportal/execution'], 'connected-desktop');
  }
  for (const name of readTools) assert.equal(MCP_TOOL_BY_NAME.get(name).risk, 'read', `${name} must be read`);
  for (const name of writeTools) assert.equal(MCP_TOOL_BY_NAME.get(name).risk, 'write', `${name} must be write`);
  for (const name of destructiveTools) assert.equal(MCP_TOOL_BY_NAME.get(name).risk, 'destructive', `${name} must be destructive`);
});

test('every irreversible BPF tool requires explicit confirmation', () => {
  for (const name of destructiveTools) {
    const tool = MCP_TOOL_BY_NAME.get(name);
    assert.ok(tool.inputSchema.required.includes('confirm'), `${name} must require confirm`);
    assert.equal(tool.inputSchema.properties.confirm.type, 'boolean');
  }
  // Changing the live state of a process people are mid-way through is not
  // undoable by re-running the tool, so it is confirmed even though it is only
  // classified as a write.
  assert.ok(MCP_TOOL_BY_NAME.get('set_business_process_flow_state').inputSchema.required.includes('confirm'));
});

test('every BPF write is bound to a revision the caller has just read', () => {
  for (const name of ['patch_business_process_flow', 'update_business_process_flow']) {
    const tool = MCP_TOOL_BY_NAME.get(name);
    assert.ok(tool.inputSchema.required.includes('expectedRevision'), `${name} must require expectedRevision`);
    assert.match(tool.inputSchema.properties.expectedRevision.description, /revision/i);
  }
});

test('the read tool can bound what it returns', () => {
  // A real BPF is roughly 12 KB of XAML and 36 KB of clientdata. Returning both
  // on every read would spend a model's context on artifacts it usually does
  // not need, so they are opt-in and the tool says so.
  const include = MCP_TOOL_BY_NAME.get('get_business_process_flow').inputSchema.properties.include;
  assert.equal(include.type, 'array');
  assert.deepEqual(include.items.enum, ['summary', 'related', 'xaml', 'clientData', 'all']);
  assert.match(MCP_TOOL_BY_NAME.get('get_business_process_flow').description, /omitted unless include/i);
});

test('clientdata is described as the process object model, not as column values', () => {
  // Describing it as "Dataverse values keyed by logical column name" leads a
  // model to send column names into a document that has none.
  for (const name of ['create_business_process_flow', 'update_business_process_flow']) {
    const schema = MCP_TOOL_BY_NAME.get(name).inputSchema.properties.clientData;
    assert.match(schema.description, /WorkflowStep/);
    assert.match(schema.description, /PageStep per stage/);
    assert.doesNotMatch(schema.description, /keyed by logical column name/);
  }
});

test('the structural pair is described on the editing tool', () => {
  const patch = MCP_TOOL_BY_NAME.get('patch_business_process_flow');
  assert.match(patch.inputSchema.properties.xamlEdits.description, /clientDataOperations/);
  assert.match(patch.inputSchema.properties.clientDataOperations.description, /xamlEdits/);
  assert.ok(patch.annotations.idempotentHint);
});

test('BPF operations allow for platform compilation time', () => {
  for (const name of [...writeTools, ...destructiveTools]) {
    assert.ok(MCP_TOOL_BY_NAME.get(name).timeoutMs >= 120_000, `${name} must allow for Dataverse compilation`);
  }
});
