// Existing desktop workflows exposed through typed, bounded MCP contracts.
// Keep API execution on the desktop; this module contains no tenant credentials.
export function extendedTools({ tool, object, string, boolean, array, number }) {
  const integer = (description, minimum = 1, maximum = 100) => ({ type: 'integer', description, minimum, maximum });
  const id = string('Current record GUID returned by the corresponding read tool.');
  const name = { ...string('Dataverse logical or entity-set name from current metadata.'), pattern: '^[A-Za-z_][A-Za-z0-9_]*$' };
  const confirm = { type: 'boolean', const: true, description: 'Explicitly confirm the reviewed change.' };
  const scalar = { type: ['string', 'number', 'boolean', 'null'], description: 'Requested scalar setting value. Use the type from the current settings read.' };
  const row = { type: 'object', additionalProperties: true, 'x-quickerportal-dynamic-keys': true, description: 'Values keyed by exact logical column names discovered from the current table schema. This object is intentionally dynamic because every Dataverse table has different columns. Updates need the primary ID (not alternate keys). Upserts need a primary ID or @odata.id with a relative alternate-key URL, e.g. accounts(accountnumber=\u0027A1\u0027). Never repeat a target in the batch; do not guess display/schema names.' };
  const target = { logicalName: name, entitySet: name, recordId: id, primaryId: name };
  const principal = { principalId: id, principalType: { type: 'string', enum: ['systemuser', 'team'] } };
  const sharing = { ...target, ...principal };
  const sharingRequired = ['logicalName', 'entitySet', 'recordId', 'primaryId', 'principalId', 'principalType'];
  const bulk = {
    entitySet: name, logicalName: name,
    rows: array(row, 'A bounded batch; split large jobs into batches of at most 100 rows.', { minItems: 1, maxItems: 100 }),
    elastic: boolean('True only for a verified elastic table. Elastic bulk operations are not atomic.')
  };
  const bulkRequired = ['entitySet', 'logicalName', 'rows'];
  const pair = { fromLogicalName: name, toLogicalName: name, workflowIds: array(id, 'Explicitly selected flows; managed or incompatible flows are skipped and reported.', { minItems: 1, maxItems: 20, uniqueItems: true }) };
  const pairRequired = ['fromLogicalName', 'toLogicalName', 'workflowIds'];
  const write = { readOnly: false, timeoutMs: 120_000 };
  return [
    ...[['power_platform', 'power-platform'], ['sharepoint', 'sharepoint'], ['power_pages', 'powerpages']].map(([label, group]) => tool(
      `get_${label}_operation`, 'mcpOperationStatus',
      'Wait for the existing operation. Continue polling in this task until terminal; pending is not a reason to stop or ask the user to continue. Use waitMs=20000 for a bounded wait. Never repeat the original mutation. Respect approval/cancellation; inspect unknown outcomes before retrying.',
      object({ operationId: { ...string('Operation ID returned by this same MCP connection.'), minLength: 1, maxLength: 128 }, waitMs: { type:'integer',minimum:0,maximum:20000,description:'Wait for completion, up to 20 seconds. Use 20000 to avoid repeated immediate polls.' } }, ['operationId']),
      { group, execution: 'server', idempotent: true }
    )),
    tool('discover_dataverse_api', 'mcpDataverseApiCatalog', 'Search actual action/function/entity-set signatures from the selected environment CSDL. Returns bounded pages, not the entire metadata document. Includes custom APIs; permissions still apply. Metadata is cached for five minutes per account/environment; refresh after schema changes.', object({
      kind: { type: 'string', enum: ['action', 'function', 'entitySet'] }, search: string('Case-insensitive name or binding-type search.'), offset: integer('Continuation offset returned by this tool.', 0, 1_000_000), limit: integer('Page size, default 30.'), refresh: boolean('Force a fresh metadata read.')
    }), { timeoutMs: 120_000 }),
    tool('search_dataverse', 'mcpDataverseSearch', 'Search Dataverse using the configured relevance-search service. Search must be enabled and callers need access to the returned tables. Returns one bounded page; this is not an unrestricted OData request.', object({
      mode: { type: 'string', enum: ['query', 'suggest', 'autocomplete', 'status', 'statistics'] }, search: { ...string('Search terms; suggestions need at least three characters.'), maxLength: 100 }, entities: array(name, 'Optional table logical names.', { maxItems: 20 }), top: integer('Maximum results, up to 100 for query or 20 for suggestions.'), skip: integer('Query continuation offset.', 0, 100_000), filter: string('Documented Dataverse Search filter expression.'), fuzzy: boolean('Enable supported fuzzy matching.'), count: boolean('Return total matching count.')
    })),
    tool('find_duplicate_records', 'mcpDataverseDuplicates', 'Find duplicates for a candidate row using published Dataverse duplicate-detection rules. Does not create records. Empty results do not prove uniqueness if no applicable rule exists.', object({ logicalName: name, row, pageNumber: integer('Page number, default 1.', 1, 100_000), count: integer('Page size, default 50.', 1, 500) }, ['logicalName', 'row'])),
    tool('get_dataverse_changes', 'dataverseChangeTracking', 'Read an incremental change-tracking page, including deletions. Start with entitySet and an optional $select query. Pass nextLink or deltaLink back as deltaLink without editing it. Change tracking must be enabled; filter/orderby/expand/top are unsupported.', { ...object({ entitySet: name, query: string('Optional $select query only; omit filter/orderby/expand/top.'), deltaLink: { ...string('Opaque nextLink or deltaLink returned by the preceding page.'), minLength: 1 } }), anyOf: [{ required: ['entitySet'] }, { required: ['deltaLink'] }] }),
    tool('get_audit_overview', 'dataverseAuditOverview', 'Read organization auditing settings and up to 100 recent audit events. Permission failures are explicit; an empty audit collection is not evidence that auditing is enabled.'),
    tool('get_audit_detail', 'dataverseAuditDetail', 'Retrieve audited before/after values for one audit entry using RetrieveAuditDetails. Requires audit-read privileges.', object({ auditId: id }, ['auditId'])),
    tool('get_record_sharing', 'dataverseRecordAccess', 'List principals explicitly sharing this current record. This is not the complete inherited security-role access picture.', object(target, ['logicalName', 'entitySet', 'recordId', 'primaryId']), { fixedArguments: { mode: 'shared' } }),
    tool('get_principal_record_access', 'dataverseRecordAccess', 'Retrieve the effective rights of one user or team to one current record.', object(sharing, sharingRequired), { fixedArguments: { mode: 'principal' } }),
    ...[['grant_record_access', 'GrantAccess'], ['modify_record_access', 'ModifyAccess']].map(([toolName, operation]) => tool(toolName, 'dataverseRecordAccessChange', 'Change only explicit record sharing for the selected principal. Read sharing and effective access first. This does not edit role privileges.', object({ ...sharing, accessMask: { ...string('Comma-separated access rights, for example ReadAccess,WriteAccess.'), pattern: '^(ReadAccess|WriteAccess|AppendAccess|AppendToAccess|CreateAccess|DeleteAccess|ShareAccess|AssignAccess)(,\\s*(ReadAccess|WriteAccess|AppendAccess|AppendToAccess|CreateAccess|DeleteAccess|ShareAccess|AssignAccess))*$' } }, [...sharingRequired, 'accessMask']), { ...write, fixedArguments: { operation } })),
    tool('revoke_record_access', 'dataverseRecordAccessChange', 'Revoke the selected principal’s explicit sharing after reviewing current access. Inherited role rights may remain.', object({ ...sharing, confirm }, [...sharingRequired, 'confirm']), { ...write, destructive: true, fixedArguments: { operation: 'RevokeAccess' } }),
    tool('get_organization_settings', 'dataverseOrganizationSettings', 'Read current organization settings and metadata types. Updateability metadata is not proof that a setting is publicly supported; consult Microsoft documentation before changing it.', object(), { timeoutMs: 120_000 }),
    tool('update_organization_setting', 'dataverseOrganizationSettingUpdate', 'Change one documented organization setting, such as auditing, after reading its current value and type. Requires administration privileges. Returns previous value and verified readback; only change settings explicitly requested by the user.', object({ logicalName: name, value: scalar, expectedValue: scalar }, ['logicalName', 'value', 'expectedValue']), write),
    tool('get_environment_administration', 'powerPlatformEnvironmentOverview', 'Read environment-management settings and recent lifecycle operations. Availability depends on Power Platform administrator permissions; per-surface failures are returned explicitly.', object(), { timeoutMs: 120_000 }),
    tool('update_environment_management_setting', 'powerPlatformManagementSettingUpdate', 'Change one documented scalar environment-management setting returned by get_environment_administration. Requires admin permissions; reads back and verifies the value.', object({ name, value: scalar, expectedValue: scalar }, ['name', 'value', 'expectedValue']), write),
    tool('preview_bulk_records', 'dataverseBulkPlan', 'Validate a bulk record payload and discover whether the table supports the requested bulk API before submitting. This is a preview, not a write.', object({ ...bulk, operation: { type: 'string', enum: ['CreateMultiple', 'UpdateMultiple', 'UpsertMultiple'] } }, [...bulkRequired, 'operation'])),
    ...[['create_records_bulk', 'CreateMultiple'], ['update_records_bulk', 'UpdateMultiple'], ['upsert_records_bulk', 'UpsertMultiple']].map(([toolName, operation]) => tool(toolName, 'dataverseBulkExecute', 'Submit up to 100 records through the Dataverse bulk API after preview_bulk_records confirms support. Standard-table operations are atomic; elastic-table operations may partially succeed. Do not repeat a pending operation; poll its operation ID.', object(bulk, bulkRequired), { ...write, fixedArguments: { operation } })),
    tool('get_flow_connection_replacements', 'flowConnectionReferenceOptions', 'Read compatible replacement connection references for one connection key in a current cloud flow. Returns the current revision and warns about unbound targets.', object({ workflowId: id, connectionKey: string('Exact connection key from get_cloud_flow.') }, ['workflowId', 'connectionKey'])),
    tool('replace_flow_connection_reference', 'replaceFlowConnectionReference', 'Replace one connection reference using a targeted revision-checked edit. Revalidates connector compatibility and verifies the stored flow; never reconstruct the whole flow.', object({ workflowId: id, connectionKey: string('Exact current connection key.'), toLogicalName: name, expectedRevision: string('Revision from get_flow_connection_replacements.') }, ['workflowId', 'connectionKey', 'toLogicalName', 'expectedRevision']), write),
    tool('list_connection_replacement_candidates', 'connectionReferenceBulkCandidates', 'List compatible targets for an existing connection reference before planning a multi-flow replacement.', object({ fromLogicalName: name }, ['fromLogicalName'])),
    tool('preview_flow_connection_replacements', 'connectionReferenceBulkReplacePlan', 'Preview replacing a connection reference in up to 20 explicitly selected flows. Reports managed/incompatible flows and unbound targets without writing.', object(pair, pairRequired)),
    tool('apply_flow_connection_replacements', 'connectionReferenceBulkReplace', 'Apply a reviewed connection-reference replacement to up to 20 selected flows. Replans against current definitions and returns per-flow success/failure plus an undo plan. Active flows use the replacement on subsequent runs.', object({ ...pair, confirm }, [...pairRequired, 'confirm']), write),
    tool('list_dependency_scopes', 'dependencyScopes', 'List solutions and supported dependency component types before choosing a bounded analysis scope.'),
    tool('get_component_dependency_tree', 'dependencyTree', 'Traverse declared required/dependent solution-component relationships with bounded depth and node count. Dynamic references in source code are not guaranteed to be registered dependencies; inspect the returned risks and truncation warnings.', object({ objectId: id, componentType: integer('Solution component type.', 1, 100_000), name: string('Optional display label.'), requiresDepth: integer('Required-component depth, default 4.', 1, 4), dependentsDepth: integer('Dependent-component depth, default 1.', 1, 2) }, ['objectId', 'componentType']), { timeoutMs: 120_000 }),
    tool('refresh_canvas_authoring_prerequisites', 'canvasAuthoringPrerequisites', 'Recheck the local .NET/runtime prerequisites. Does not install software or change the Canvas app.', object({ force: boolean('Force rediscovery rather than using the cached prerequisite result.') })),
    tool('disconnect_canvas_authoring', 'canvasAuthoringDisconnect', 'Disconnect this Canvas authoring session without publishing the app. Review pending changes before disconnecting.', object({ appId: id }, ['appId']), write)
  ];
}
